SELECT TOP (1000) [Id]
      ,[Endereco]
      ,[Preco]
      ,[Descricao]
      ,[Area]
      ,[NumeroQuartos]
      ,[NumeroBanheiros]
      ,[TemGaragem]
      ,[DataCadastro]
  FROM [ImobiliariaDb].[dbo].[Imoveis]
